// Egm2008Geoid_test.cpp — Tests for liteaero::geodesy::Egm2008Geoid.
//
// Tests use a small synthetic grid written to a temp file in test setup;
// the production grid is generated by the build_terrain Python pipeline
// from the PROJ-managed EGM2008 datum-shift grid (LS-T3 wiring).

#define _USE_MATH_DEFINES
#include "geodesy/Egm2008Geoid.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <vector>

using namespace liteaero::geodesy;

namespace {

// Write a small EGM2008 grid file with the documented binary layout.  The
// caller supplies the geographic extent and per-cell undulation values.
std::filesystem::path writeSyntheticGrid(
    const std::string& fixture_name,
    double lat_min_deg, double lat_max_deg,
    double lon_min_deg, double lon_max_deg,
    std::uint32_t n_lat, std::uint32_t n_lon,
    const std::vector<float>& values)  // size = n_lat * n_lon, row-major
{
    const auto out =
        std::filesystem::temp_directory_path() / (fixture_name + ".egm2008");
    std::ofstream f(out, std::ios::binary | std::ios::trunc);

    const char magic[8] = {'E', 'G', 'M', '2', '0', '0', '8', '\0'};
    f.write(magic, sizeof(magic));
    const std::uint32_t version = 1;
    f.write(reinterpret_cast<const char*>(&version), sizeof(version));
    f.write(reinterpret_cast<const char*>(&lat_min_deg), sizeof(double));
    f.write(reinterpret_cast<const char*>(&lat_max_deg), sizeof(double));
    f.write(reinterpret_cast<const char*>(&lon_min_deg), sizeof(double));
    f.write(reinterpret_cast<const char*>(&lon_max_deg), sizeof(double));
    f.write(reinterpret_cast<const char*>(&n_lat), sizeof(std::uint32_t));
    f.write(reinterpret_cast<const char*>(&n_lon), sizeof(std::uint32_t));
    f.write(reinterpret_cast<const char*>(values.data()),
            static_cast<std::streamsize>(values.size() * sizeof(float)));
    f.close();
    return out;
}

}  // namespace

// ---------------------------------------------------------------------------
// Construction errors
// ---------------------------------------------------------------------------

TEST(Egm2008GeoidTest, Construct_MissingFile_Throws) {
    EXPECT_THROW(
        Egm2008Geoid("does_not_exist_xyzabc.egm2008"),
        std::runtime_error);
}

// ---------------------------------------------------------------------------
// Direct grid lookups
// ---------------------------------------------------------------------------

TEST(Egm2008GeoidTest, Undulation_AtGridCorner_ReturnsExactValue) {
    // 2x2 grid covering [-1, +1] degrees in both lat and lon.
    const std::vector<float> values = {
        -10.0f,  -5.0f,    // (lat=-1, lon=-1) ; (lat=-1, lon=+1)
         +5.0f, +10.0f,    // (lat=+1, lon=-1) ; (lat=+1, lon=+1)
    };
    const auto path = writeSyntheticGrid(
        "egm2008_corner_test", -1.0, 1.0, -1.0, 1.0, 2, 2, values);
    Egm2008Geoid geoid(path);

    const double deg = M_PI / 180.0;
    EXPECT_FLOAT_EQ(geoid.undulation_m(-1.0 * deg, -1.0 * deg), -10.0f);
    EXPECT_FLOAT_EQ(geoid.undulation_m(-1.0 * deg,  1.0 * deg),  -5.0f);
    EXPECT_FLOAT_EQ(geoid.undulation_m( 1.0 * deg, -1.0 * deg),  +5.0f);
    EXPECT_FLOAT_EQ(geoid.undulation_m( 1.0 * deg,  1.0 * deg), +10.0f);
}

TEST(Egm2008GeoidTest, Undulation_AtGridCenter_BilinearAverage) {
    // 2x2 grid; (0, 0) is the geometric center.  Bilinear interp gives the
    // mean of the four corner values.
    const std::vector<float> values = {-10.0f, -5.0f, +5.0f, +10.0f};
    const auto path = writeSyntheticGrid(
        "egm2008_center_test", -1.0, 1.0, -1.0, 1.0, 2, 2, values);
    Egm2008Geoid geoid(path);

    const float expected = (-10.0f + -5.0f + 5.0f + 10.0f) / 4.0f;  // 0
    EXPECT_NEAR(geoid.undulation_m(0.0, 0.0), expected, 1e-6f);
}

TEST(Egm2008GeoidTest, Undulation_OnEdgeMidpoint_LinearAverage) {
    const std::vector<float> values = {-10.0f, -5.0f, +5.0f, +10.0f};
    const auto path = writeSyntheticGrid(
        "egm2008_edge_test", -1.0, 1.0, -1.0, 1.0, 2, 2, values);
    Egm2008Geoid geoid(path);

    const double deg = M_PI / 180.0;
    // Midpoint of south edge (lat=-1, lon=0): mean of (-10, -5) = -7.5
    EXPECT_NEAR(geoid.undulation_m(-1.0 * deg, 0.0), -7.5f, 1e-6f);
    // Midpoint of east edge (lat=0, lon=+1): mean of (-5, +10) = 2.5
    EXPECT_NEAR(geoid.undulation_m(0.0, 1.0 * deg),   2.5f, 1e-6f);
}

TEST(Egm2008GeoidTest, Undulation_OutsideGrid_ClampsToBoundary) {
    const std::vector<float> values = {-10.0f, -5.0f, +5.0f, +10.0f};
    const auto path = writeSyntheticGrid(
        "egm2008_clamp_test", -1.0, 1.0, -1.0, 1.0, 2, 2, values);
    Egm2008Geoid geoid(path);

    const double deg = M_PI / 180.0;
    // 5 degrees south of the grid: clamps to (lat=-1, lon=0) edge midpoint.
    EXPECT_NEAR(geoid.undulation_m(-5.0 * deg, 0.0), -7.5f, 1e-6f);
}

// ---------------------------------------------------------------------------
// MSL <-> ellipsoidal conversion
// ---------------------------------------------------------------------------

TEST(Egm2008GeoidTest, RoundTrip_WgsToMslAndBack_RestoresOriginal) {
    // 2x2 grid with arbitrary undulation values across the test point.
    const std::vector<float> values = {-32.5f, -32.0f, -33.0f, -32.5f};
    const auto path = writeSyntheticGrid(
        "egm2008_roundtrip_test", -1.0, 1.0, -1.0, 1.0, 2, 2, values);
    Egm2008Geoid geoid(path);

    const float h_wgs84 = 100.0f;
    const float h_msl   = geoid.wgs84ToMsl_m(0.0, 0.0, h_wgs84);
    const float h_back  = geoid.mslToWgs84_m(0.0, 0.0, h_msl);
    EXPECT_NEAR(h_back, h_wgs84, 1e-3f);
}

TEST(Egm2008GeoidTest, WgsToMsl_AddsUndulationCorrectly) {
    // Constant +10m undulation across the grid: h_MSL = h_WGS84 - 10.
    const std::vector<float> values = {10.0f, 10.0f, 10.0f, 10.0f};
    const auto path = writeSyntheticGrid(
        "egm2008_const_test", -1.0, 1.0, -1.0, 1.0, 2, 2, values);
    Egm2008Geoid geoid(path);

    EXPECT_FLOAT_EQ(geoid.wgs84ToMsl_m(0.0, 0.0, 100.0f), 90.0f);
    EXPECT_FLOAT_EQ(geoid.mslToWgs84_m(0.0, 0.0,  90.0f), 100.0f);
}
