#pragma once
// Egm2008Geoid.hpp — EGM2008 geoid undulation lookup.
//
// Provides bilinear-interpolated geoid undulation N(lat, lon) on a regular
// lat/lon grid loaded from a project-private binary file.  The file is
// generated by the Python build_terrain pipeline (LS-T3 wiring) from the
// PROJ-managed EGM2008 datum-shift grid.
//
// Usage (typical):
//   liteaero::geodesy::Egm2008Geoid geoid(grid_file_path);
//   float h_msl = geoid.wgs84ToMsl_m(lat_rad, lon_rad, h_wgs84_m);
//
// The relationship is h_WGS84 = h_MSL + N, so:
//   h_MSL  = h_WGS84 - N
//   h_WGS84 = h_MSL + N
//
// Design authority: docs/architecture/live_sim_view.md §Implementation Roadmap
// Task LS-T2.

#include <cstdint>
#include <filesystem>
#include <vector>

namespace liteaero::geodesy {

// ---------------------------------------------------------------------------
// File format (little-endian throughout)
// ---------------------------------------------------------------------------
//
//   [8  bytes]  magic "EGM2008\0"
//   [4  bytes]  format_version (uint32) = 1
//   [8  bytes]  lat_min_deg (float64)   — south edge of grid
//   [8  bytes]  lat_max_deg (float64)   — north edge of grid
//   [8  bytes]  lon_min_deg (float64)   — west edge of grid
//   [8  bytes]  lon_max_deg (float64)   — east edge of grid
//   [4  bytes]  n_lat (uint32)          — number of latitude samples
//   [4  bytes]  n_lon (uint32)          — number of longitude samples
//   [N  bytes]  grid (float32, row-major: lat-major outer, lon-major inner)
//
// Sample i (0..n_lat-1) is at lat_min_deg + i * (lat_max_deg - lat_min_deg) / (n_lat-1).
// Sample j (0..n_lon-1) is at lon_min_deg + j * (lon_max_deg - lon_min_deg) / (n_lon-1).
// Grid value at (i, j) = grid[i * n_lon + j] is the undulation N in metres.

class Egm2008Geoid {
public:
    /// Load a geoid grid from a binary file in the format above.  Throws
    /// std::runtime_error on file open or format errors.
    explicit Egm2008Geoid(const std::filesystem::path& grid_file);

    /// Geoid undulation N (m) at the given geodetic point.  Bilinear
    /// interpolation on the loaded grid.  Out-of-range queries clamp to the
    /// grid boundary (geoid varies smoothly so clamping is safe within the
    /// PROJ EGM2008 grid's global coverage).
    float undulation_m(double lat_rad, double lon_rad) const;

    /// Convert WGS84 ellipsoidal height to MSL (orthometric) at (lat, lon).
    /// h_MSL = h_WGS84 - N(lat, lon).
    float wgs84ToMsl_m(double lat_rad, double lon_rad, float h_wgs84_m) const;

    /// Convert MSL (orthometric) height to WGS84 ellipsoidal at (lat, lon).
    /// h_WGS84 = h_MSL + N(lat, lon).
    float mslToWgs84_m(double lat_rad, double lon_rad, float h_msl_m) const;

private:
    double lat_min_deg_ = 0.0;
    double lat_max_deg_ = 0.0;
    double lon_min_deg_ = 0.0;
    double lon_max_deg_ = 0.0;
    std::uint32_t n_lat_ = 0;
    std::uint32_t n_lon_ = 0;
    std::vector<float> grid_;  // row-major, size = n_lat * n_lon
};

}  // namespace liteaero::geodesy
